#!/bin/bash

process_usage() { echo "$*" >&2; exit 1; }
arg_required() { if [ -z "$OPTARG" ]; then process_usage "Argument required for --$flag option"; fi; }
help() {
  cat <<HELP
Usage: db2Ly [OPTIONS] SCORE_ID|SCORE_NAME [OUTPUT_FILE]

Converts a MusicXML database record to LilyPond.

SCORE_ID: the database record value in the score table, field id.

SCORE_NAME: the database record value in the score table, field score_name.

OUTPUT_FILE: the LilyPond output filename.
If no OUTPUT_FILE argument is given, output is to stdout.

Options:
  -b, --include-breaks	include page and system breaks in the LilyPond output
  -v, --verbose		verbose output while processing
HELP
exit 0
}
version() { echo "1.0"; }

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

SCORE_ID=''
SCORENAME=''
INCLUDE_BREAKS=''
VERBOSE=''

while getopts 'bv' flag; do
  case "${flag}" in
    b) INCLUDE_BREAKS="INCLUDE_BREAKS" ;;
    v) VERBOSE="VERBOSE" ;;
  esac
done
shift $(expr $OPTIND - 1)
INPUT=$1
if [[ $INPUT =~ ^[0-9]+$ ]] ; then
  SCORE_ID=$INPUT
else
  SCORENAME=$INPUT
fi
OUTPUT_FILE=$2
if [ -z $OUTPUT_FILE ]; then OUTPUT_FILE="STDOUT"; fi

java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.Db2Ly SCORENAME="$SCORENAME" SCORE_ID=$SCORE_ID OUTPUT_FILE=$OUTPUT_FILE $INCLUDE_BREAKS $VERBOSE
exit $?
