#!/bin/bash

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

SCORE_ID=''
SCORENAME=''
VERBOSE=''

while getopts 'v' flag; do
  case "${flag}" in
    v) VERBOSE="VERBOSE" ;;
  esac
done
shift $(expr $OPTIND - 1)
INPUT=$1
if [[ $INPUT =~ ^[0-9]+$ ]] ; then
  SCORE_ID=$INPUT
else
  SCORENAME=$INPUT
fi
OUTPUT_FILE=$2

java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.Db2Pdf SCORENAME="$SCORENAME" SCORE_ID=$SCORE_ID OUTPUT_FILE=$OUTPUT_FILE $VERBOSE
exit $?
