#!/bin/bash

process_usage() { echo "$*" >&2; exit 1; }
arg_required() { if [ -z "$OPTARG" ]; then process_usage "Argument required for --$flag option"; fi; }
help() {
  cat <<HELP
Usage: ly2Pdf [INPUT_FILE] OUTPUT_FILE

Converts LilyPond to a PDF file.

INPUT_FILE: the LilyPond input filename.
LilyPond input can be from stdin in place of an INPUT_FILE argument.

OUTPUT_FILE: the PDF output filename.

HELP
exit 0
}
version() { echo "1.0"; }

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

INPUT_FILE=''
INPUT_DATA=''
TEMP_FILE=''

if [[ -p /dev/stdin ]]
    then
    INPUT_DATA=$(cat -)
    TEMP_FILE="$(mktemp /tmp/XXXXXX.ly)"
    echo "$INPUT_DATA" > $TEMP_FILE
    INPUT_FILE=$TEMP_FILE
fi

if [ -z "$INPUT_DATA" ]
then
  INPUT_FILE=$1
  OUTPUT_FILE=$2
else
  OUTPUT_FILE=$1
fi

java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.Ly2Pdf INPUT_FILE=$INPUT_FILE OUTPUT_FILE=$OUTPUT_FILE
RETURN_CODE=$?

if [ -f "$TEMP_FILE" ]; then rm $TEMP_FILE; fi
exit $RETURN_CODE;
