#!/bin/bash

process_usage() { echo "$*" >&2; exit 1; }
help() {
  cat <<HELP
Usage: musicXml2Ly [OPTIONS] [INPUT_FILE] [OUTPUT_FILE]

Converts MusicXML to LilyPond.

INPUT_FILE: the MusicXML input filename.
MusicXML input can be from stdin in place of an INPUT_FILE argument.

OUTPUT_FILE: the LilyPond output filename.
If no OUTPUT_FILE argument is given, output is to stdout.

Options:
  -b, --include-breaks	include page and system breaks in the LilyPond output
  -v, --verbose		verbose output while processing
HELP
exit 0
}
version() { echo "1.0"; }

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

INCLUDE_BREAKS=''
VERBOSE=''
INPUT_DATA=''
TEMP_FILE=''

if [[ -p /dev/stdin ]]
    then
    INPUT_DATA=$(cat -)
    TEMP_FILE="$(mktemp /tmp/XXXXXX.xml)"
    echo "$INPUT_DATA" > $TEMP_FILE
    INPUT_FILE=$TEMP_FILE
fi

while getopts 'bhv-:' flag; do
  if [ "$flag" = "-" ]; then
    flag="${OPTARG%%=*}"
    OPTARG="${OPTARG#$flag}"
    OPTARG="${OPTARG#=}"
  fi
  case "${flag}" in
    b|include-breaks) INCLUDE_BREAKS="INCLUDE_BREAKS" ;;
    h|help) help ;;
    v|verbose) VERBOSE="VERBOSE" ;;
    version) version ;;
    ??*) process_usage "Unrecognized option --$flag" ;;
    ?) exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1)
if [ -z "$INPUT_DATA" ]
then
  INPUT_FILE=$1
  OUTPUT_FILE=$2
else
  OUTPUT_FILE=$1
fi
if [ -z $OUTPUT_FILE ]; then OUTPUT_FILE="STDOUT"; fi

java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.MusicXml2Ly INPUT_FILE=$INPUT_FILE OUTPUT_FILE=$OUTPUT_FILE $INCLUDE_BREAKS $VERBOSE
RETURN_CODE=$?

if [ -f "$TEMP_FILE" ]; then rm $TEMP_FILE; fi
exit $RETURN_CODE;
