#!/bin/bash

help() {
  cat <<HELP
Usage: musicXmlDiff INPUT_FILE COMPARE_FILE

Compares two MusicXML files.
Diff output is to stdout.
The two MusicXML files are first standardized using xmllint before the diff is performed.
Unlike Unix diff, all '<' lines appear before all '>' lines.

INPUT_FILE: the MusicXML input filename.

COMPARE_FILE: the filename of the MusicXML file that the INPUT_FILE is compared to.

HELP
exit 0
}
version() { echo "1.0"; }

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

INPUT_FILE=$1
COMPARE_FILE=$2

java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.MusicXmlDiff INPUT_FILE=$INPUT_FILE COMPARE_FILE=$COMPARE_FILE

exit $?
