#!/bin/bash

# SET THIS TO DIRECTORY JAR FILE RESIDES IN
JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
# SET THIS TO JAR FILE NAME
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

DEBUG=''
INPUT_DATA=''
INPUT_FILE=''
TEMP_FILE=''
RETURN_CODE=0

if [[ -p /dev/stdin ]]
    then
    INPUT_DATA=$(cat -)
    TEMP_FILE="$(mktemp /tmp/XXXXXX.xml)"
    echo "$INPUT_DATA" > $TEMP_FILE
    INPUT_FILE=$TEMP_FILE
fi

while getopts 'd' flag; do
  case "${flag}" in
    d) DEBUG="DEBUG" ;;
  esac
done
shift $(expr $OPTIND - 1)
if [ -z "$INPUT_DATA" ]
then
  INPUT_FILE=$1
  SCORENAME=$2
else
  SCORENAME=$1
  if [ -z "$SCORENAME" ]
  then
    echo "Error: Score name argument is required" 1>&2
    RETURN_CODE=1
  fi
fi

if [ $RETURN_CODE -eq 0 ]
then
  java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.MusicXml2Db INPUT_FILE=$INPUT_FILE SCORENAME="$SCORENAME" $DEBUG
  RETURN_CODE=$?
fi

if [ -f "$TEMP_FILE" ]; then rm $TEMP_FILE; fi
exit $RETURN_CODE;
