#!/bin/bash

process_usage() { echo "$*" >&2; exit 1; }
arg_required() { if [ -z "$OPTARG" ]; then process_usage "Argument required for --$flag option"; fi; }
help() {
  cat <<HELP
Usage: db2MusicXml [OPTIONS] SCORE_ID|SCORE_NAME [OUTPUT_FILE]

Converts a MusicXML database record to MusicXML.

SCORE_ID: the database record value in the score table, field id.

SCORE_NAME: the database record value in the score table, field score_name.

OUTPUT_FILE: the XML output filename.

If filename has .mxl extension, output file is zipped, and the -z|--zipped-file option is required.

If no OUTPUT_FILE argument is given, output is to stdout.

Options:
  -c, --skip-comments	 don't include XML comments and processing instructions in the XML output
  -v, --verbose		displays processing output
  -z ZIPPED_FILE_NAME, --zipped-file=ZIPPED_FILE_NAME  name of XML file included in zipped .mxl output file
HELP
exit 0
}
version() { echo "1.0"; }

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

SCORE_ID=''
SCORENAME=''
SKIP_COMMENTS=''
VERBOSE=''
ZIPPED_FILE=''

while getopts 'chvz:-:' flag; do
  if [ "$flag" = "-" ]; then
    flag="${OPTARG%%=*}"
    OPTARG="${OPTARG#$flag}"
    OPTARG="${OPTARG#=}"
  fi
  case "${flag}" in
    c|skip-comments) SKIP_COMMENTS="SKIP_COMMENTS" ;;
    h|help) help ; exit 0 ;;
    v|verbose) VERBOSE="VERBOSE" ;;
    version) version ; exit 0 ;;
    z|zipped-file) arg_required; ZIPPED_FILE="${OPTARG}" ;;
    ??*) process_usage "Unrecognized option --$flag" ;;
    ?) exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1)
INPUT=$1
if [[ $INPUT =~ ^[0-9]+$ ]] ; then
  SCORE_ID=$INPUT
else
  SCORENAME=$INPUT
fi
OUTPUT_FILE=$2
if [ -z $OUTPUT_FILE ]; then OUTPUT_FILE="STDOUT"; fi

java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.Db2MusicXml SCORENAME="$SCORENAME" SCORE_ID=$SCORE_ID OUTPUT_FILE=$OUTPUT_FILE ZIPPED_FILE=$ZIPPED_FILE $SKIP_COMMENTS $VERBOSE
exit #?
