#!/bin/bash

process_usage() { echo "$*" >&2; exit 1; }
help() {
  cat <<HELP
Usage: musicXml2Db [OPTIONS] [INPUT_FILE] SCORE_NAME

Converts MusicXML to a MusicXML database record.

INPUT_FILE: the MusicXML input filename.

MusicXML input can be from stdin in place of an INPUT_FILE argument.

SCORE_NAME: the database record score name.

The score name must be unique in the database.

Options:
  -v, --verbose		displays processing output
HELP
exit 0
}
version() { echo "1.0"; }

JAR_DIR=/home/curtis/.m2/repository/org/curtis/musicxml/1.0
JAR_FILE=musicxml-1.0-jar-with-dependencies.jar

CLASSPATH=${JAR_DIR}/${JAR_FILE}

VERBOSE=''
INPUT_DATA=''
INPUT_FILE=''
TEMP_FILE=''
RETURN_CODE=0

if [[ -p /dev/stdin ]]
    then
    INPUT_DATA=$(cat -)
    TEMP_FILE="$(mktemp /tmp/XXXXXX.xml)"
    echo "$INPUT_DATA" > $TEMP_FILE
    INPUT_FILE=$TEMP_FILE
fi

while getopts 'hv-:' flag; do
  if [ "$flag" = "-" ]; then
    flag="${OPTARG%%=*}"
    OPTARG="${OPTARG#$flag}"
    OPTARG="${OPTARG#=}"
  fi
  case "${flag}" in
    h|help) help ;;
    v|verbose) VERBOSE="VERBOSE" ;;
    version) version ; exit 0 ;;
    ??*) process_usage "Unrecognized option --$flag" ;;
    ?) exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1)
if [ -z "$INPUT_DATA" ]
then
  INPUT_FILE=$1
  SCORENAME=$2
else
  SCORENAME=$1
  if [ -z "$SCORENAME" ]
  then
    echo "Error: Score name argument is required" 1>&2
    RETURN_CODE=1
  fi
fi

if [ $RETURN_CODE -eq 0 ]
then
  java -classpath ${CLASSPATH} -Dnet.sf.ehcache.enableShutdownHook=true org.curtis.musicxml.bin.MusicXml2Db INPUT_FILE=$INPUT_FILE SCORENAME="$SCORENAME" $VERBOSE
  RETURN_CODE=$?
fi

if [ -f "$TEMP_FILE" ]; then rm $TEMP_FILE; fi
exit $RETURN_CODE;
